image: samueldebruyn/debian-git

pipelines:
  custom: # Pipelines that are triggered manually via the Bitbucket GUI
    init: # -- First time init
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init -v --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://reservation-plugin.demo.cmsminds.com/public_html/wp-content/plugins/easy-reservations/
  branches:
    master:
      - step:
          deployment: staging
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init -v --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://reservation-plugin.demo.cmsminds.com/public_html/wp-content/plugins/easy-reservations/